analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    inference_failure_on_function_invocation: ignore
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: ignore
